[package]
name = "ch8-simple"
version = "0.1.0"
authors = ["Tim McNamara <author@rustinaction.com>"]
edition = "2018"

[dependencies]
reqwest = { version="0.11.18", features = ["blocking", "json"] }

